# Generated by Django 4.0.5 on 2022-07-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_fee',
        ),
    ]
